# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='static/banners/'),
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='recommendations',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='text',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='competition',
            name='url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
