# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_auto_20170218_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpt', to='voices.Voice'),
        ),
    ]
