# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0003_competition_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='converted_file',
            field=models.FileField(null=True, upload_to='voices'),
        ),
    ]
