# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0005_auto_20170219_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='url',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
