# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0007_auto_20170224_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='winner',
        ),
    ]
