# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0009_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voice',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='voices'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='original_file',
            field=models.FileField(upload_to='voices'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='state',
            field=models.CharField(choices=[('P', 'EN PROCESO'), ('C', 'CONVERTIDO')], max_length=1),
        ),
    ]
